### ISSUE TITLE
https://david-dm.org is down

### ISSUE THREAD

**Issue by e-cloud** [alanshaw/david#123] opened 2016-09-25 08:19 UTC

**Comment by doug-wade** [comment] 2016-10-04 09:57
![screenshot from 2016-10-04 02-54-31](https://cloud.githubusercontent.com/assets/3477707/19070009/33d93860-89de-11e6-869c-e0460d0acf18.png)

**Comment by rreusser** [comment] 2016-10-12 14:53
It seems to load *sometimes*, but is very slow and intermittent. I'm sure it's not free to host this service, so I hope it's not the case that it's just economically infeasible. At any rate, am very grateful for the service and will hope for the best!

**Comment by alanshaw** [comment] 2016-10-14 14:38
Looks likely that the recent slowness and disruption to service was caused by the [memory leak](https://github.com/nodejs/node/commit/7a59449478) in Node.js 6.7. This has now been resolved with an upgrade to 6.8.

**Closed by alanshaw** 2016-10-14 14:38 UTC

**Comment by rreusser** [comment] 2016-10-14 14:42
Thought maybe it was the server/traffic ratio, but didn't expect a memory leak. Thanks for fixing!

**Comment by alanshaw** [comment] 2016-10-14 15:05
David is generally fine with the traffic, it's only serving ~10 requests per second. It occasionally suffers when github/npm have problems (since it relies on them heavily).

The server has been upgraded recently from a single core, 1GB VM -> dual core, 2GB VM so it _was_ a lot better until we upgraded to 6.7. Node.js really doesn't like it when it gets low on memory, my experience is that it pegs the CPU at 100% and sometimes never recovers. My guess is that the garbage collector is constantly running and not able to collect anything. Understandably this causes responses to be super slow. I've read about this behaviour being experienced by others as well.

![graphs](https://cloud.githubusercontent.com/assets/152863/19392250/ded3dc42-9227-11e6-956a-b8ec6ba18b86.png)

**Comment by hirako2000** [comment] 2016-10-19 11:35
Keep seeing down as well - perhaps restart the process once a day - the few seconds down time will be better than the frequent slowness/outage.

**Comment by dkniffin** [comment] 2016-11-15 14:46
Yep, I'm seeing slow david-dm badges as well, eg: https://github.com/KeitIG/museeks

![image](https://cloud.githubusercontent.com/assets/1680080/20310025/5824bce8-ab18-11e6-8cfa-59f9c24e6aa4.png)

**Comment by kevincaradant** [comment] 2016-12-20 14:07
Hi

Today, I tried to sign in on it but the website seems to be very very slow so I get everytime a Internal Server Error. Am I the only to have this bug ?

Thank you

**Comment by ismay** [comment] 2017-01-19 11:07
@dkniffin Me too, both the david-dm website and badges (through shields.io) are very slow, for multiple repos.

**Comment by alanshaw** [comment] 2017-01-19 11:21
Hi all, thanks for your concerns - I'll be doing something about this in the coming weeks.

**Comment by pixelass** [comment] 2017-02-01 23:13
Today:

<img width="786" alt="screen shot 2017-02-02 at 12 12 52 am" src="https://cloud.githubusercontent.com/assets/1148334/22530562/5ee32040-e8dc-11e6-8feb-1af359fc0132.png">

and later:

<img width="902" alt="screen shot 2017-02-02 at 12 12 24 am" src="https://cloud.githubusercontent.com/assets/1148334/22530565/62fec6d4-e8dc-11e6-91bb-bd78484009cb.png">

**Comment by MeLlamoPablo** [comment] 2017-02-07 11:34
I'm having the same 504 issues as well. Just letting you know, no pressure.

**Comment by ibujs** [comment] 2017-02-07 15:38
For some reason, these happen a lot of times to me.

**Comment by pixelass** [comment] 2017-02-07 16:19
downtimes seem to be >90% in the last half year.

**Comment by alanshaw** [comment] 2017-02-07 20:32
please see https://github.com/alanshaw/david-www/issues/357#issuecomment-278117903

**Comment by ibujs** [comment] 2017-02-08 11:02
ay, then let's be patient and stop complaining about it, if that is the case.
